name: Test workflow
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  Integration_test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/iac-reshaping/docker/builder:v1.0.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        id: build_and_test
        timeout-minutes: 1
        run: |
          make test_integration
          ./test/run_instruction_testbench
